version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - pern_network
    volumes:
      - ./server:/app
    env_file: ./.env
    command: npm run dev
    ports:
      - 5000:5000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - pern_network
    volumes:
      - ./client:/app
    command: npm start
    ports:
      - 3000:3000

networks:
  pern_network:
