version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    env_file: ./.env
    command: npm run dev
    ports:
      - 3000:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    command: npm start
    ports:
      - 3001:3000
