version: "3"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file: ./.env
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
